include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    join_return_with_assignment: true
    always_declare_return_types: true
    avoid_types_on_closure_parameters: true
    avoid_returning_null_for_future: true
    unawaited_futures: true
    avoid_void_async: true
    unnecessary_await_in_return: true
    use_build_context_synchronously: true

analyzer:
  errors:
    todo: ignore
  exclude:
    - lib/generated/*
